###########
# site.title

title:    'Mimicraft'
subtitle: 'Mimicking 2D Images into 3D Minecraft Models'


#########################
# more settings

markdown: kramdown

exclude:
- README.md
- LICENSE.md
